let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Exit Vim if NERDTree is the only window remaining in the only tab.
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | call feedkeys(":quit\<CR>:\<BS>") | endif

call plug#begin()
Plug 'tpope/vim-eunuch'
Plug 'yegappan/mru'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'preservim/nerdtree'
Plug 'liuchengxu/vista.vim'
Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app && npx --yes yarn install' }
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'airblade/vim-gitgutter'
Plug 'vim-airline/vim-airline'
Plug 'sainnhe/gruvbox-material'
Plug 'vim-airline/vim-airline-themes'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'yianwillis/vimcdoc'
Plug 'ryanoasis/vim-devicons'
Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
Plug 'mbbill/undotree'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-fugitive'
Plug 'mg979/vim-visual-multi'
Plug 'easymotion/vim-easymotion'
if has('mac')
  Plug 'ybian/smartim'
endif
Plug 'preservim/nerdcommenter'
call plug#end()

filetype on
syntax enable
set encoding=utf-8
set number
set nobackup
set nocompatible
set foldmethod=syntax
set foldlevel=99
let g:coc_global_extensions = ['coc-rust-analyzer', 'coc-go', 'coc-vimlsp', 'coc-json', 'coc-yaml']
let g:vista_default_executive = 'coc'
let g:vista#renderer#enable_icon = 0
let g:NERDTreeShowLineNumbers = 1
let g:NERDTreeShowHidden = 1
let g:NERDSpaceDelims = 1
let g:NERDDefaultAlign = 'left'
let g:NERDToggleCheckAllLines = 1

set list
set listchars=tab:»-,trail:-,eol:↲,extends:»,precedes:«,nbsp:%

" vim-gitgutter used to do this by default:
highlight! link SignColumn LineNr
let g:gitgutter_override_sign_column_highlight = 1
set updatetime=250
colorscheme gruvbox-material
let g:airline_theme = 'gruvbox_material'

let g:go_gopls_enabled = 1
let g:go_gopls_options = ['-remote=auto']
let g:go_def_mode='gopls'
let g:go_info_mode='gopls'
let g:go_referrers_mode = 'gopls'

if has('termguicolors') && ($COLORTERM == 'truecolor' || $COLORTERM == '24bit')
  " enable true color
  set termguicolors
endif


function! ShowDocumentation()
  if CocAction('hasProvider', 'hover')
    call CocActionAsync('doHover')
  else
    call feedkeys('K', 'in')
  endif
endfunction

" GoTo code navigation
nmap <silent>K :call ShowDocumentation()<CR>
nmap <silent>gd <Plug>(coc-definition)
nmap <silent>gy <Plug>(coc-type-definition)
nmap <silent>gi <Plug>(coc-implementation)
nmap <silent>gr <Plug>(coc-references)
nmap <silent>[g <Plug>(coc-diagnostic-prev)
nmap <silent>]g <Plug>(coc-diagnostic-next)
nmap <leader>ac <Plug>(coc-codeaction)

nnoremap <leader>nf :NERDTreeFocus<CR>
nnoremap <leader>nt :NERDTreeToggle<CR>
nnoremap <F5> :UndotreeToggle<CR>
nnoremap <F8> :Vista!!<CR>

let g:VM_maps = {}
let g:VM_maps["Add Cursor Down"]      = '<C-j>'
let g:VM_maps["Add Cursor Up"]        = '<C-k>'

command! -nargs=? Fold :call CocAction('fold', <f-args>)
command! -nargs=? Format :call CocAction('format', <f-args>)
autocmd BufEnter *.png,*.jpg,*gif,*pdf exec "! imgcat ".expand("%") | :bw
autocmd BufEnter * if winnr('$') == 1 && bufname() == "__vista__" | execute "normal! :q!\<CR>" | endif

let g:smartim_default = 'com.apple.keylayout.ABC'

if has('persistent_undo')
  set undofile
  set undodir=~/.vim/undodir
  if !isdirectory(&undodir)
    call mkdir(&undodir, 'p', 0700)
  endif
endif

if has('mouse')
  if has('gui_running') || (&term =~ 'xterm' && !has('mac'))
    set mouse=a
  else
    set mouse=nvi
  endif
endif

